// Content drawn from research-paper-agents/docs/CASE_STUDY.md. Only claims the
// write-up itself makes are used here, including what was NOT measured.

export const caseStudy = {
  eyebrow: "Case Study",
  title: "A research paper writer where code checks the citations, not the model",
  intro:
    "Drafting a paper with an LLM fails in two ways that matter more than fluency. It invents or misattributes citations, and it drifts from the brief. I built Research Paper Agents so that code catches both, and so a person approves the direction before any drafting effort is spent.",
  links: {
    github: "https://github.com/Prekshabarjatya/research-paper-agents",
    writeup:
      "https://github.com/Prekshabarjatya/research-paper-agents/blob/main/docs/CASE_STUDY.md",
    live: "https://research-paper-agents.vercel.app/",
  },
  stats: [
    { value: "7", label: "agent roles in one LangGraph workflow" },
    { value: "67", label: "automated tests, including real Postgres" },
    { value: "3 to 4 min", label: "and about 35k to 39k tokens per paper" },
    { value: "~6", label: "live runs used to find the problems below" },
  ],
  pipeline: [
    { name: "Brief analyst", note: "Reads word limit, sections and citation style", gate: false },
    { name: "Topic strategist", note: "Proposes a topic", gate: true },
    { name: "Source scout", note: "Searches OpenAlex and Semantic Scholar, keeps only papers whose DOI resolves in Crossref", gate: false },
    { name: "Thesis writer", note: "Proposes a thesis", gate: true },
    { name: "Outliner", note: "Plans sections and assigns sources to each", gate: false },
    { name: "Drafter", note: "Writes each section from its own sources", gate: false },
    { name: "Critic", note: "Chooses between rewrite and find more sources, up to 4 rounds", gate: false },
  ],
  decisions: [
    {
      title: "Fixed graph, not an LLM supervisor",
      body: "Routing is plain code. It is cheaper, easy to test, and fits free-tier rate limits. The only dynamic choices are the two human approvals and the critic's rewrite or find-more-sources call.",
    },
    {
      title: "Citations verified in code",
      body: "A source is kept only if its DOI resolves in Crossref and the title and year match. This is the one guarantee that should not depend on model behavior.",
    },
    {
      title: "Reference list generated by code",
      body: "The writer can only cite ids of verified sources, and code builds the bibliography, so the model cannot invent a reference entry.",
    },
    {
      title: "Human approval at topic and thesis",
      body: "These are the cheapest points to correct direction, before any drafting tokens are spent.",
    },
    {
      title: "Postgres as run store and queue",
      body: "One datastore holds runs and jobs. Progress is checkpointed after every step, so a run resumes after a crash or deploy.",
    },
  ],
  findings: [
    {
      problem: "A prompt went over the provider's token cap",
      evidence: "A thesis request was 8,779 tokens against a limit of 8,000.",
      fix: "Cap sources at 15, trim abstracts, and show the critic only the body and the sources it cites.",
    },
    {
      problem: "Off-topic sources in the pool",
      evidence: "42 verified sources included an edge-computing paper for a last-mile delivery query.",
      fix: "Rank by relevance first, verify in rank order, and stop when the pool is full.",
    },
    {
      problem: "The length limit was missed",
      evidence: "The first draft was 2,086 words against a 1,500 maximum, because the count included a 369-word reference list.",
      fix: "Count the body only, on the text the reader actually sees.",
    },
    {
      problem: "An invented statistic",
      evidence: "The critic flagged a \"12% fuel reduction\" that no source supported.",
      fix: "The writer may not state numbers missing from the abstracts, and the critic flags any that slip through.",
    },
    {
      problem: "A section came back with one word",
      evidence: "Draft 3 of one run had an Analysis section of a single word.",
      fix: "Retry degenerate output and treat any section under 40 words as a hard issue.",
    },
  ],
  notMeasured: [
    "Paper quality. There is no golden set and no human rating of argument quality.",
    "Whether each sentence is faithful to its source. Every reference is matched to a Crossref record, but sentence-level faithfulness is judged only by an LLM reviewer, which is not proof.",
    "A finished live run approved by the reviewer. The live runs that finished were all flagged for human review, mostly for word count, and the daily token quota ran out before the later length fixes could be confirmed.",
  ],
  lostInTheMiddle: {
    title: "Where \"lost in the middle\" fits",
    paragraphs: [
      "Liu et al. (2024) report that language models use information at the start and end of a long prompt better than information buried in the middle. Several choices in this project happen to agree with that: keeping only the 15 most relevant sources, ranking before prompting, and giving each section only its own sources.",
      "Those choices were driven by token limits and observed failures, not by the paper, and this project did not test its claim. The prompts are also short, a few thousand tokens, far below the lengths where the effect was reported.",
    ],
    experiment:
      "A small test is planned but not run yet, because it needs model quota. It would move the most relevant sources between first, middle and last position across 6 to 8 real assignments and compare citation validity, section coverage and reviewer approval. The expected result is little or no difference at these lengths, and a null result would be reported as one.",
  },
} as const;
